spring:
  application:
    name: studit
  redis:
    host: localhost
    port: 6379
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/studitdb?characterEncoding=UTF-8
    username: root
    password: 13579
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 0dbf8ff608e5c9d905e3b8f95a9ca48c
            client-secret: { CLIENT_SECRET } # 필요할 수도 있음
            redirect-uri: http://localhost:8080/auth/callback
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname, profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

kakao:
  client-id: 0dbf8ff608e5c9d905e3b8f95a9ca48c
  redirect-uri: http://localhost:8080/api/auth/callback
  logout_redirect_uri: http://localhost:8080/api/auth/kakao-logout
  service_app_admin_key: adc00d63db10846333bc186022ccd551
  client-secret: TnQEcPvKF61CSeUh7tuUeXTg4eWbhT5g

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    org.springframework.security.oauth2: DEBUG

jwt:
  secret: xAjB14zxBjipIlsClFPwvB177HwxkuTnOSjGLjJSNY0=